/**
 * IPIP-NEO-120 — 120 items, 5 domains, 30 facets, 4 items per facet.
 *
 * Source (public domain, International Personality Item Pool):
 *   https://ipip.ori.org/new120ItemNEOFacetsKey.htm
 *   https://ipip.ori.org/newNEOFacetsKey.htm
 *
 * Reference scoring key adapted from Johnson, J.A. (2014).
 * "Measuring thirty facets of the Five Factor Model with a 120-item public
 * domain inventory: Development of the IPIP-NEO-120." Journal of Research in
 * Personality, 51, 78-89.
 *
 * Domains: O (Openness), C (Conscientiousness), E (Extraversion),
 *          A (Agreeableness), N (Neuroticism).
 *
 * Facets per domain (Johnson IPIP-NEO mapping):
 *   N1 Anxiety, N2 Anger, N3 Depression, N4 Self-Consciousness,
 *      N5 Immoderation, N6 Vulnerability
 *   E1 Friendliness, E2 Gregariousness, E3 Assertiveness, E4 Activity Level,
 *      E5 Excitement-Seeking, E6 Cheerfulness
 *   O1 Imagination, O2 Artistic Interests, O3 Emotionality,
 *      O4 Adventurousness, O5 Intellect, O6 Liberalism
 *   A1 Trust, A2 Morality, A3 Altruism, A4 Cooperation, A5 Modesty,
 *      A6 Sympathy
 *   C1 Self-Efficacy, C2 Orderliness, C3 Dutifulness, C4 Achievement-Striving,
 *      C5 Self-Discipline, C6 Cautiousness
 *
 * IMPORTANT — pt-BR translations:
 * The translations below are working translations produced for this skeleton
 * and are flagged `pending_validation`. They MUST be reviewed by a Brazilian
 * psychometrist before clinical/HR use. See README "Pendências".
 */

import type { ItemDescriptor } from "../../_contract/schema";

export type IpipDomain = "O" | "C" | "E" | "A" | "N";

export type IpipFacet =
  | "n1_anxiety"
  | "n2_anger"
  | "n3_depression"
  | "n4_self_consciousness"
  | "n5_immoderation"
  | "n6_vulnerability"
  | "e1_friendliness"
  | "e2_gregariousness"
  | "e3_assertiveness"
  | "e4_activity_level"
  | "e5_excitement_seeking"
  | "e6_cheerfulness"
  | "o1_imagination"
  | "o2_artistic_interests"
  | "o3_emotionality"
  | "o4_adventurousness"
  | "o5_intellect"
  | "o6_liberalism"
  | "a1_trust"
  | "a2_morality"
  | "a3_altruism"
  | "a4_cooperation"
  | "a5_modesty"
  | "a6_sympathy"
  | "c1_self_efficacy"
  | "c2_orderliness"
  | "c3_dutifulness"
  | "c4_achievement_striving"
  | "c5_self_discipline"
  | "c6_cautiousness";

export interface IpipItem extends ItemDescriptor {
  domain: IpipDomain;
  facet: IpipFacet;
  reverse_keyed: boolean;
  scale_kind: "likert5";
  /** Original IPIP item code/text (English) for traceability. */
  source_en: string;
  /** Per-item translation status — should be flipped to "validated" after review. */
  translation: "pending_validation" | "validated";
}

/* ------------------------------------------------------------------ */
/* Items                                                              */
/* ------------------------------------------------------------------ */

/**
 * Order follows Johnson (2014) IPIP-NEO-120 published order.
 * `+` = keyed positively (raw value), `-` = reverse-keyed (6 - raw on a 1-5 scale).
 */
export const IPIP_NEO_120_ITEMS: IpipItem[] = [
  // ---------- Items 1-4: N1 Anxiety ----------
  {
    item_id: "ipip-neo-120-001",
    facet: "n1_anxiety",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Worry about things.",
    text: "Preocupo-me com as coisas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-002",
    facet: "n1_anxiety",
    domain: "N",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am not easily bothered by things.",
    text: "Não me incomodo facilmente com as coisas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-003",
    facet: "n1_anxiety",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am afraid of many things.",
    text: "Tenho medo de muitas coisas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-004",
    facet: "n1_anxiety",
    domain: "N",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am relaxed most of the time.",
    text: "Fico relaxado(a) na maior parte do tempo.",
    translation: "pending_validation",
  },

  // ---------- Items 5-8: E1 Friendliness ----------
  {
    item_id: "ipip-neo-120-005",
    facet: "e1_friendliness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Make friends easily.",
    text: "Faço amigos com facilidade.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-006",
    facet: "e1_friendliness",
    domain: "E",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am hard to get to know.",
    text: "Sou difícil de conhecer.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-007",
    facet: "e1_friendliness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Warm up quickly to others.",
    text: "Crio proximidade rapidamente com outras pessoas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-008",
    facet: "e1_friendliness",
    domain: "E",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Often feel uncomfortable around others.",
    text: "Frequentemente me sinto desconfortável perto de outras pessoas.",
    translation: "pending_validation",
  },

  // ---------- Items 9-12: O1 Imagination ----------
  {
    item_id: "ipip-neo-120-009",
    facet: "o1_imagination",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Have a vivid imagination.",
    text: "Tenho uma imaginação vívida.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-010",
    facet: "o1_imagination",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Seldom daydream.",
    text: "Raramente fico em devaneios.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-011",
    facet: "o1_imagination",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Like to get lost in thought.",
    text: "Gosto de me perder em pensamentos.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-012",
    facet: "o1_imagination",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Do not have a good imagination.",
    text: "Não tenho uma boa imaginação.",
    translation: "pending_validation",
  },

  // ---------- Items 13-16: A1 Trust ----------
  {
    item_id: "ipip-neo-120-013",
    facet: "a1_trust",
    domain: "A",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Trust others.",
    text: "Confio nas pessoas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-014",
    facet: "a1_trust",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Believe that others have good intentions.",
    text: "Acredito que as outras pessoas têm boas intenções.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-015",
    facet: "a1_trust",
    domain: "A",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Trust what people say.",
    text: "Confio no que as pessoas dizem.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-016",
    facet: "a1_trust",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Distrust people.",
    text: "Desconfio das pessoas.",
    translation: "pending_validation",
  },

  // ---------- Items 17-20: C1 Self-Efficacy ----------
  {
    item_id: "ipip-neo-120-017",
    facet: "c1_self_efficacy",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Complete tasks successfully.",
    text: "Realizo tarefas com sucesso.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-018",
    facet: "c1_self_efficacy",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Excel in what I do.",
    text: "Me destaco no que faço.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-019",
    facet: "c1_self_efficacy",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Handle tasks smoothly.",
    text: "Lido com tarefas sem dificuldade.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-020",
    facet: "c1_self_efficacy",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Know how to get things done.",
    text: "Sei como fazer as coisas acontecerem.",
    translation: "pending_validation",
  },

  // ---------- Items 21-24: N2 Anger ----------
  {
    item_id: "ipip-neo-120-021",
    facet: "n2_anger",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Get angry easily.",
    text: "Fico irritado(a) com facilidade.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-022",
    facet: "n2_anger",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Get irritated easily.",
    text: "Me aborreço com facilidade.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-023",
    facet: "n2_anger",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Lose my temper.",
    text: "Perco a paciência.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-024",
    facet: "n2_anger",
    domain: "N",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Rarely get irritated.",
    text: "Raramente me aborreço.",
    translation: "pending_validation",
  },

  // ---------- Items 25-28: E2 Gregariousness ----------
  {
    item_id: "ipip-neo-120-025",
    facet: "e2_gregariousness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Love large parties.",
    text: "Adoro festas grandes.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-026",
    facet: "e2_gregariousness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Talk to a lot of different people at parties.",
    text: "Converso com várias pessoas diferentes em festas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-027",
    facet: "e2_gregariousness",
    domain: "E",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Prefer to be alone.",
    text: "Prefiro ficar sozinho(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-028",
    facet: "e2_gregariousness",
    domain: "E",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Avoid crowds.",
    text: "Evito multidões.",
    translation: "pending_validation",
  },

  // ---------- Items 29-32: O2 Artistic Interests ----------
  {
    item_id: "ipip-neo-120-029",
    facet: "o2_artistic_interests",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Believe in the importance of art.",
    text: "Acredito na importância da arte.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-030",
    facet: "o2_artistic_interests",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Like music.",
    text: "Gosto de música.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-031",
    facet: "o2_artistic_interests",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Do not like poetry.",
    text: "Não gosto de poesia.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-032",
    facet: "o2_artistic_interests",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Do not enjoy going to art museums.",
    text: "Não gosto de visitar museus de arte.",
    translation: "pending_validation",
  },

  // ---------- Items 33-36: A2 Morality ----------
  {
    item_id: "ipip-neo-120-033",
    facet: "a2_morality",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Use flattery to get ahead.",
    text: "Uso bajulação para conseguir o que quero.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-034",
    facet: "a2_morality",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Use others for my own ends.",
    text: "Uso os outros para meus próprios fins.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-035",
    facet: "a2_morality",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Cheat to get ahead.",
    text: "Trapaceio para conseguir vantagem.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-036",
    facet: "a2_morality",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Take advantage of others.",
    text: "Levo vantagem em cima dos outros.",
    translation: "pending_validation",
  },

  // ---------- Items 37-40: C2 Orderliness ----------
  {
    item_id: "ipip-neo-120-037",
    facet: "c2_orderliness",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Like order.",
    text: "Gosto de ordem.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-038",
    facet: "c2_orderliness",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Like to tidy up.",
    text: "Gosto de organizar e arrumar.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-039",
    facet: "c2_orderliness",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Leave a mess in my room.",
    text: "Deixo bagunça no meu quarto.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-040",
    facet: "c2_orderliness",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Leave my belongings around.",
    text: "Deixo meus pertences espalhados.",
    translation: "pending_validation",
  },

  // ---------- Items 41-44: N3 Depression ----------
  {
    item_id: "ipip-neo-120-041",
    facet: "n3_depression",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Often feel blue.",
    text: "Frequentemente me sinto para baixo.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-042",
    facet: "n3_depression",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Dislike myself.",
    text: "Não gosto de mim mesmo(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-043",
    facet: "n3_depression",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am often down in the dumps.",
    text: "Frequentemente me sinto desanimado(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-044",
    facet: "n3_depression",
    domain: "N",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Feel comfortable with myself.",
    text: "Me sinto à vontade comigo mesmo(a).",
    translation: "pending_validation",
  },

  // ---------- Items 45-48: E3 Assertiveness ----------
  {
    item_id: "ipip-neo-120-045",
    facet: "e3_assertiveness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Take charge.",
    text: "Tomo a frente das situações.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-046",
    facet: "e3_assertiveness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Try to lead others.",
    text: "Tento liderar os outros.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-047",
    facet: "e3_assertiveness",
    domain: "E",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Wait for others to lead the way.",
    text: "Espero os outros tomarem a iniciativa.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-048",
    facet: "e3_assertiveness",
    domain: "E",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Keep in the background.",
    text: "Fico em segundo plano.",
    translation: "pending_validation",
  },

  // ---------- Items 49-52: O3 Emotionality ----------
  {
    item_id: "ipip-neo-120-049",
    facet: "o3_emotionality",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Experience my emotions intensely.",
    text: "Vivencio minhas emoções intensamente.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-050",
    facet: "o3_emotionality",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Feel others' emotions.",
    text: "Sinto as emoções dos outros.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-051",
    facet: "o3_emotionality",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Rarely notice my emotional reactions.",
    text: "Raramente percebo minhas reações emocionais.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-052",
    facet: "o3_emotionality",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Don't understand people who get emotional.",
    text: "Não entendo pessoas que ficam emotivas.",
    translation: "pending_validation",
  },

  // ---------- Items 53-56: A3 Altruism ----------
  {
    item_id: "ipip-neo-120-053",
    facet: "a3_altruism",
    domain: "A",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Make people feel welcome.",
    text: "Faço as pessoas se sentirem bem-vindas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-054",
    facet: "a3_altruism",
    domain: "A",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Anticipate the needs of others.",
    text: "Antecipo as necessidades dos outros.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-055",
    facet: "a3_altruism",
    domain: "A",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Love to help others.",
    text: "Amo ajudar os outros.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-056",
    facet: "a3_altruism",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am indifferent to the feelings of others.",
    text: "Sou indiferente aos sentimentos dos outros.",
    translation: "pending_validation",
  },

  // ---------- Items 57-60: C3 Dutifulness ----------
  {
    item_id: "ipip-neo-120-057",
    facet: "c3_dutifulness",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Try to follow the rules.",
    text: "Procuro seguir as regras.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-058",
    facet: "c3_dutifulness",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Keep my promises.",
    text: "Cumpro minhas promessas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-059",
    facet: "c3_dutifulness",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Break rules.",
    text: "Quebro regras.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-060",
    facet: "c3_dutifulness",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Break my promises.",
    text: "Quebro minhas promessas.",
    translation: "pending_validation",
  },

  // ---------- Items 61-64: N4 Self-Consciousness ----------
  {
    item_id: "ipip-neo-120-061",
    facet: "n4_self_consciousness",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am easily intimidated.",
    text: "Sou facilmente intimidado(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-062",
    facet: "n4_self_consciousness",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am afraid that I will do the wrong thing.",
    text: "Tenho medo de fazer a coisa errada.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-063",
    facet: "n4_self_consciousness",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Find it difficult to approach others.",
    text: "Acho difícil me aproximar de outras pessoas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-064",
    facet: "n4_self_consciousness",
    domain: "N",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am not embarrassed easily.",
    text: "Não me constranjo facilmente.",
    translation: "pending_validation",
  },

  // ---------- Items 65-68: E4 Activity Level ----------
  {
    item_id: "ipip-neo-120-065",
    facet: "e4_activity_level",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am always busy.",
    text: "Estou sempre ocupado(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-066",
    facet: "e4_activity_level",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am always on the go.",
    text: "Estou sempre em movimento.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-067",
    facet: "e4_activity_level",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Do a lot in my spare time.",
    text: "Faço muitas coisas no meu tempo livre.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-068",
    facet: "e4_activity_level",
    domain: "E",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Like to take it easy.",
    text: "Gosto de levar a vida com calma.",
    translation: "pending_validation",
  },

  // ---------- Items 69-72: O4 Adventurousness ----------
  {
    item_id: "ipip-neo-120-069",
    facet: "o4_adventurousness",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Prefer variety to routine.",
    text: "Prefiro variedade à rotina.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-070",
    facet: "o4_adventurousness",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Prefer to stick with things that I know.",
    text: "Prefiro me ater àquilo que conheço.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-071",
    facet: "o4_adventurousness",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Dislike changes.",
    text: "Não gosto de mudanças.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-072",
    facet: "o4_adventurousness",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am attached to conventional ways.",
    text: "Sou apegado(a) a maneiras convencionais.",
    translation: "pending_validation",
  },

  // ---------- Items 73-76: A4 Cooperation ----------
  {
    item_id: "ipip-neo-120-073",
    facet: "a4_cooperation",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Love a good fight.",
    text: "Adoro uma boa briga.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-074",
    facet: "a4_cooperation",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Yell at people.",
    text: "Grito com as pessoas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-075",
    facet: "a4_cooperation",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Insult people.",
    text: "Insulto as pessoas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-076",
    facet: "a4_cooperation",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Get back at others.",
    text: "Me vingo dos outros.",
    translation: "pending_validation",
  },

  // ---------- Items 77-80: C4 Achievement-Striving ----------
  {
    item_id: "ipip-neo-120-077",
    facet: "c4_achievement_striving",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Go straight for the goal.",
    text: "Vou direto ao objetivo.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-078",
    facet: "c4_achievement_striving",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Work hard.",
    text: "Trabalho duro.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-079",
    facet: "c4_achievement_striving",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Do just enough work to get by.",
    text: "Faço só o suficiente para passar.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-080",
    facet: "c4_achievement_striving",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Put little time and effort into my work.",
    text: "Coloco pouco tempo e esforço no meu trabalho.",
    translation: "pending_validation",
  },

  // ---------- Items 81-84: N5 Immoderation ----------
  {
    item_id: "ipip-neo-120-081",
    facet: "n5_immoderation",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Often eat too much.",
    text: "Frequentemente como demais.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-082",
    facet: "n5_immoderation",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Don't know why I do some of the things I do.",
    text: "Não sei por que faço algumas das coisas que faço.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-083",
    facet: "n5_immoderation",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Do things I later regret.",
    text: "Faço coisas das quais me arrependo depois.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-084",
    facet: "n5_immoderation",
    domain: "N",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Never spend more than I can afford.",
    text: "Nunca gasto mais do que posso pagar.",
    translation: "pending_validation",
  },

  // ---------- Items 85-88: E5 Excitement-Seeking ----------
  {
    item_id: "ipip-neo-120-085",
    facet: "e5_excitement_seeking",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Love excitement.",
    text: "Amo emoções fortes.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-086",
    facet: "e5_excitement_seeking",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Seek adventure.",
    text: "Busco aventura.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-087",
    facet: "e5_excitement_seeking",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Enjoy being reckless.",
    text: "Gosto de ser ousado(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-088",
    facet: "e5_excitement_seeking",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Act wild and crazy.",
    text: "Ajo de forma livre e ousada.",
    translation: "pending_validation",
  },

  // ---------- Items 89-92: O5 Intellect ----------
  {
    item_id: "ipip-neo-120-089",
    facet: "o5_intellect",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Like to solve complex problems.",
    text: "Gosto de resolver problemas complexos.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-090",
    facet: "o5_intellect",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Avoid philosophical discussions.",
    text: "Evito discussões filosóficas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-091",
    facet: "o5_intellect",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Have difficulty understanding abstract ideas.",
    text: "Tenho dificuldade em entender ideias abstratas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-092",
    facet: "o5_intellect",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am not interested in abstract ideas.",
    text: "Não me interesso por ideias abstratas.",
    translation: "pending_validation",
  },

  // ---------- Items 93-96: A5 Modesty ----------
  {
    item_id: "ipip-neo-120-093",
    facet: "a5_modesty",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Believe that I am better than others.",
    text: "Acredito que sou melhor que os outros.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-094",
    facet: "a5_modesty",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Think highly of myself.",
    text: "Tenho uma opinião muito alta de mim mesmo(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-095",
    facet: "a5_modesty",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Have a high opinion of myself.",
    text: "Tenho uma alta opinião sobre mim.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-096",
    facet: "a5_modesty",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Boast about my virtues.",
    text: "Me gabo das minhas virtudes.",
    translation: "pending_validation",
  },

  // ---------- Items 97-100: C5 Self-Discipline ----------
  {
    item_id: "ipip-neo-120-097",
    facet: "c5_self_discipline",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Get chores done right away.",
    text: "Realizo minhas tarefas imediatamente.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-098",
    facet: "c5_self_discipline",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am always prepared.",
    text: "Estou sempre preparado(a).",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-099",
    facet: "c5_self_discipline",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Waste my time.",
    text: "Desperdiço meu tempo.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-100",
    facet: "c5_self_discipline",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Have difficulty starting tasks.",
    text: "Tenho dificuldade em começar tarefas.",
    translation: "pending_validation",
  },

  // ---------- Items 101-104: N6 Vulnerability ----------
  {
    item_id: "ipip-neo-120-101",
    facet: "n6_vulnerability",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Panic easily.",
    text: "Entro em pânico facilmente.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-102",
    facet: "n6_vulnerability",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Become overwhelmed by events.",
    text: "Me sinto sobrecarregado(a) pelos acontecimentos.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-103",
    facet: "n6_vulnerability",
    domain: "N",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Feel that I'm unable to deal with things.",
    text: "Sinto que não consigo lidar com as coisas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-104",
    facet: "n6_vulnerability",
    domain: "N",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Remain calm under pressure.",
    text: "Permaneço calmo(a) sob pressão.",
    translation: "pending_validation",
  },

  // ---------- Items 105-108: E6 Cheerfulness ----------
  {
    item_id: "ipip-neo-120-105",
    facet: "e6_cheerfulness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Radiate joy.",
    text: "Irradio alegria.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-106",
    facet: "e6_cheerfulness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Have a lot of fun.",
    text: "Me divirto bastante.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-107",
    facet: "e6_cheerfulness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Love life.",
    text: "Amo a vida.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-108",
    facet: "e6_cheerfulness",
    domain: "E",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Look at the bright side of life.",
    text: "Olho para o lado positivo da vida.",
    translation: "pending_validation",
  },

  // ---------- Items 109-112: O6 Liberalism ----------
  {
    item_id: "ipip-neo-120-109",
    facet: "o6_liberalism",
    domain: "O",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Tend to vote for liberal political candidates.",
    text: "Tendo a votar em candidatos progressistas.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-110",
    facet: "o6_liberalism",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Believe in one true religion.",
    text: "Acredito em uma única religião verdadeira.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-111",
    facet: "o6_liberalism",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Tend to vote for conservative political candidates.",
    text: "Tendo a votar em candidatos conservadores.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-112",
    facet: "o6_liberalism",
    domain: "O",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Believe that too much tax money goes to support artists.",
    text: "Acredito que muito dinheiro de impostos vai para apoiar artistas.",
    translation: "pending_validation",
  },

  // ---------- Items 113-116: A6 Sympathy ----------
  {
    item_id: "ipip-neo-120-113",
    facet: "a6_sympathy",
    domain: "A",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Sympathize with the homeless.",
    text: "Sinto compaixão pelas pessoas em situação de rua.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-114",
    facet: "a6_sympathy",
    domain: "A",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Feel sympathy for those who are worse off than myself.",
    text: "Sinto compaixão por quem está em situação pior do que a minha.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-115",
    facet: "a6_sympathy",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Am not interested in other people's problems.",
    text: "Não me interesso pelos problemas dos outros.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-116",
    facet: "a6_sympathy",
    domain: "A",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Try not to think about the needy.",
    text: "Procuro não pensar nas pessoas necessitadas.",
    translation: "pending_validation",
  },

  // ---------- Items 117-120: C6 Cautiousness ----------
  {
    item_id: "ipip-neo-120-117",
    facet: "c6_cautiousness",
    domain: "C",
    reverse_keyed: false,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Avoid mistakes.",
    text: "Evito erros.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-118",
    facet: "c6_cautiousness",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Choose my words with care.",
    text: "Escolho minhas palavras com cuidado.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-119",
    facet: "c6_cautiousness",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Jump into things without thinking.",
    text: "Me jogo nas coisas sem pensar.",
    translation: "pending_validation",
  },
  {
    item_id: "ipip-neo-120-120",
    facet: "c6_cautiousness",
    domain: "C",
    reverse_keyed: true,
    scale_kind: "likert5",
    language: "pt-BR",
    source_en: "Make rash decisions.",
    text: "Tomo decisões precipitadas.",
    translation: "pending_validation",
  },
];

if (IPIP_NEO_120_ITEMS.length !== 120) {
  // sanity check at module load
  throw new Error(
    `IPIP-NEO-120 must have exactly 120 items (got ${IPIP_NEO_120_ITEMS.length}).`,
  );
}

/* ------------------------------------------------------------------ */
/* Lookup helpers                                                     */
/* ------------------------------------------------------------------ */

export const ITEMS_BY_ID: Record<string, IpipItem> = Object.fromEntries(
  IPIP_NEO_120_ITEMS.map((item) => [item.item_id, item]),
);

export const FACETS: IpipFacet[] = [
  "n1_anxiety",
  "n2_anger",
  "n3_depression",
  "n4_self_consciousness",
  "n5_immoderation",
  "n6_vulnerability",
  "e1_friendliness",
  "e2_gregariousness",
  "e3_assertiveness",
  "e4_activity_level",
  "e5_excitement_seeking",
  "e6_cheerfulness",
  "o1_imagination",
  "o2_artistic_interests",
  "o3_emotionality",
  "o4_adventurousness",
  "o5_intellect",
  "o6_liberalism",
  "a1_trust",
  "a2_morality",
  "a3_altruism",
  "a4_cooperation",
  "a5_modesty",
  "a6_sympathy",
  "c1_self_efficacy",
  "c2_orderliness",
  "c3_dutifulness",
  "c4_achievement_striving",
  "c5_self_discipline",
  "c6_cautiousness",
];

export const FACET_TO_DOMAIN: Record<IpipFacet, IpipDomain> = {
  n1_anxiety: "N",
  n2_anger: "N",
  n3_depression: "N",
  n4_self_consciousness: "N",
  n5_immoderation: "N",
  n6_vulnerability: "N",
  e1_friendliness: "E",
  e2_gregariousness: "E",
  e3_assertiveness: "E",
  e4_activity_level: "E",
  e5_excitement_seeking: "E",
  e6_cheerfulness: "E",
  o1_imagination: "O",
  o2_artistic_interests: "O",
  o3_emotionality: "O",
  o4_adventurousness: "O",
  o5_intellect: "O",
  o6_liberalism: "O",
  a1_trust: "A",
  a2_morality: "A",
  a3_altruism: "A",
  a4_cooperation: "A",
  a5_modesty: "A",
  a6_sympathy: "A",
  c1_self_efficacy: "C",
  c2_orderliness: "C",
  c3_dutifulness: "C",
  c4_achievement_striving: "C",
  c5_self_discipline: "C",
  c6_cautiousness: "C",
};

export const DOMAINS: IpipDomain[] = ["O", "C", "E", "A", "N"];
